#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Mon Apr 29 12:09:45 CST 2019
#define FWConfiguration YIZWzZkiLhXHGQSu
#define fwDidFinishLaunchingWithOptions PgdoLZIsfbstCDZP
#define fwJpushDidReceiveNotificationResponse jbeKKCJEKkrVGktJ
#define fwRunOnHomeViewControllerBecomeActive CwDQlvxQuXUGnKXP
#define fwLanguage lZughfRdvAKPNuAC
#define urlString NSLFLoEbCKietyZI
#define weakSelf nxIPqfZHatrVZRuC
#define lcStatus wtqJcDjhNLNQPIso
#define lcUrlString zznKDErQmgJOOTTs
#define AdvertistingObject lenhLvdIVidMOUws
#define adWebView AqCrqyGinZxzquzm
#define AD_DURATION TUjRRtUTDAFUeFXo
#define showAdvertistingView ZlKLVLJLvFzPtnNc
#define removeAdvertistingView LmEXEePTNoaQVmxn
#define trimURL nfmmfyjjeRKYFgfh
#define sourceString sGbPgQIKQmevHdTH
#define isChinaArea GZiTliFCfYwGCNgM
#define leftConstraint stRicblAVfwcbnrO
#define rightConstraint pYhsGmtgVkEOagQD
#define topConstraint frMeVQGybBlpyZWJ
#define bottomConstraint mvCvoHfWzonqcfMf
#define rmSuperview MlvMnDpAAqLRxfdn
#define destinationString HdyaySfskmCzmfMi
#define isLanguage MvddeZOQrzyEiJkT
#define leanCloudAppId ZtciPSwWWneVKWfA
#define leanCloudAppKey vrACKhppgWIvkquE
#define leanCloudClassName sujoNHTeNwqILYep
#define leanCloudBoolColumnName qtZttEEvWcltGgPt
#define leanCloudUrlColumnName tEIzabQQEiAVwPnW
#define LeanCloudObject KZLAqnUdxmadElTO
#define getLeanCloudInfo DeWfBSzeiwANnQYj
#define dataQuery1 DqzgiVTEpFrCBwre
#define avObject1 tKabvHYjhaQUCAoU
#define AreaJudge HLczIsyhToZwpBAQ
#define isChinaArea KBzJpTlOuXRgFhzl
#define showAdView RQjPKCernKEcylxN
#define removeAdView xBumLUJpIjWFQjxl
#define globalIsArea uICNykIzJuLAjVYz
#define globalIsEnable DmMsBMeYABGewBtS
#define globalMainUrl kDWkyEQveZqZHlYX
#define globalNotificationUrl GUZLFUEAbhmtAQYk
#define description OmVQjPAsBNBYoCXQ
#define ClosureWrapper wAJcjNmRVgjhDHJq
#define SwipeGestureRecognizerClosureWrapper ADdMwDJpaqRYLiKE
#define Tools QehOKKaGONyRfHkz
#define getOutermostView UwqHqgPalPAZXeNT
#define getViewOfAbsoluteFame TxRcldBCjjdVuzRF
#define originX dWANcerREHPNRAXd
#define originY ACfqjWAMelNrfrwC
#define startIndicator ZNdxHeaKNxDXhmST
#define indicatorContentView YOrFDbtUJidKbplI
#define topCons fJXGURMUCegybXvI
#define bottomCons uXVEZZdyWQCcrsGE
#define leadCons yONCUjdfLgVQutKc
#define trailCons PFXbXEZHBROGAxgP
#define indicatorView XbmWHOSIxLbCYxpa
#define centerXCons fNSrKRSkfAgfTeMF
#define centerYCons SRrcKgfUMRkROJCi
#define cancelBtn tgCGgpZySlwSEPRJ
#define topCons1 kTCGUjPeQkCpbYSy
#define bottomCons1 RJFYIJJjpLlRQGeu
#define leadCons1 DQcurQnUVEwVaFCD
#define trailCons1 IokZiMgvIwkkzoHG
#define stopIndicator HOYjyGNKEecbExOt
#define resizeImageLimited wSVFVzJeKqlGEseU
#define httpConnect lHfcCAjGADqBPoWn
#define downloadImage nGuURpiQrnWsXKAb
#define downloadJasonDataAsDictionary XFLFHZXFgSUfTWeX
#define downloadJasonDataAsArray GdRDbuWLtIMZIFqs
#define backToViewController lpBNVkIzriSsQDLx
#define ViewController sTmOhZwAldtgMOOs
#define StyledPageControl cRlCAwBJgcUYKCQK
#define resultArray xGiSwJaXIaSIrBLo
#define adsArray pDgSeQPVLzEVZyxZ
#define adScrollView AIhUswJQEWgJRAqK
#define pageControl oxDcQzCKBUeHPDOD
#define pageControlIsChangingPage ZlohYkTPsteJYNBo
#define forward cMdEgymyRRjqeceX
#define topBarAdUrl BYbbYlLNIEINiJjz
#define ASIHTTPRequest bphVUntvpfUneMBt
#define _currentPage RTsWurWhlrhoRDOO
#define tableView IjeQqdQRTLORvvEs
#define httpRequests LqoxtlfWCiTdNnxF
#define homeButton WRDHcCodXMGDWLOD
#define featureButton xQdfYLEEFzWNQFmk
#define containerView vYcDwvVnfnYmFSlp
#define mContainerVCArr BiQErJpqMjEIJHTr
#define mTabBarButtonArr YFYQzgKByZVNreBr
#define tabBarTitles YSfJsGmwmpuulyet
#define tabBarImages GaeOaEwCZwYhiWLv
#define tabBarColor ROBizZivhXbdtTwK
#define tabBarTitleColor AkVREqGDrDwJEZzm
#define dataQuery1 YWmWgZHDEVnLyhol
#define avObject1 zCKNmedOYdqtnhac
#define adController ixSGwpxKiueKCYyZ
#define language FcLtacxWxtJKVYnI
#define dataQuery2 bNXxYTZqmlvsdXex
#define avObject2 YJZBnxOKRqWsLPhE
#define dest mJKcVcchnAuNGOqW
#define button01DidTapped pJNBVEZqilNKbiMc
#define storyboard uGOEGKgCAEcZUXvR
#define dVC tGOpElEqpSGJIcEz
#define setBottomTab dCiPopQKyTetzklA
#define btnViewColor yFvTbMJXGFQjYbdW
#define btnBgColor cAZtJAzTUxATkJie
#define btnBorderColor KYCfZVuOSezCglKa
#define btnView01 kqgBAJXfilgdheSi
#define button01 qJhspUeOdrjUuiUA
#define btnSelectRect yKRFiiSrcDWUtfAD
#define contextSelect YXOPEMNrnKLsfhoj
#define btnSelectColor IpMMBcXcAMSyLYlu
#define btnSelectImage UUqNdMTFvKZHDBTq
#define btnNormalRect JQRGduLLCdRUCLux
#define contextNormal DjVndMGjtkGqqcrI
#define btnNormalColor xeChwCkssOccoulX
#define btnNormalImage LnjnOZFbIinfAvjf
#define refresh zPBZtbFfAkBgBrVb
#define loadClientInfo YBRjkCYLdwqgzbRR
#define requests aNPcGjEHnWtumhJf
#define request POaZhrJhQGiuDzSx
#define responseData ZdgRXSFYYYiWKOiS
#define ret KZMBXUuaRDbyzbAE
#define _result EHRmvQdKmdtgGNWz
#define loadTopbarAd SUoKCCfNzmKGPJok
#define loadAds sJSbEmsEEihMbasm
#define loadMoreData aATeQIMUTKhROZJt
#define loadData prfTGQTVDFmZsSTQ
#define urlStr uIeVjIoYSDAEnJSV
#define info JUHRKzkdVtJcwZHv
#define MyIdentifier ojAAMLupfBLkzqKf
#define detailViewController efGaTEjHhJihOdRw
#define tOWebViewController LedwjfaOlYBwYeyl
#define bgColor wahgLEfJLmUcLGbU
#define customView OCwqUdlKghAdKZjU
#define headerLabel wxtqXCJLfMHCyuEl
#define Btn QEAYTLkXincYDDCJ
#define gotoUrl dtHHipnvJPiasxtx
#define dd oSigkqLnbFVPGafj
#define buildHeader QSozjLgwTGdvNwIG
#define flash wwqxFLapXXFlFQGx
#define setupPage NQLGTOjpjMkczkEu
#define pageWidth TKeNVwjNZbSuocAX
#define page UpCjxsZtNNvuhGsv
#define changePage VOzwiLAVuuLsialk
#define pageControlPageDidChange SJcIDNrxYONDyUCC
#define uploadIDFAData CvaUNBymvCWkjoTs
#define _client_id DRviZSTKHKYhUbWV
#define rawData reWNZSRhgvwdnEmZ
#define checkServerStatus jwYPdBEBaGeAGdHx
#define isNeedUpdate bmznEpnNtqkYuHML
#define description MDCUOUsRrFgQZTKw
#define alertCtrl CJnpNJfqpiFpkiDK
#define cancelAction XoYnVBDIdqjVMwzw
#define confirmAction NktGvQmtYLwCYwtr
#define ADWKWebViewController JCGmZUWVRZhiGtgX
#define webViewURL VHZmIaJSkanfqVNz
#define layoutBottomBarHeight gJUkaxelyEppReiw
#define hostReachability MpyRpGOkmSPnGpTT
#define internetReachability uSAWzUNVjrgFwDzL
#define isLoadFinish yUErjFBXIfemGlrl
#define isLandscape SaskHhHdTKxYJtPa
#define wkwebView riwvnbsYQPvnmzAN
#define noNetView xqntdhIAGlvRhMar
#define alertView xCmPYSCEddqmZOLO
#define bottomBarView HSiNzHlzzKCRGitR
#define activityIndicatorView ZmrIzVKvuISQAgkL
#define bottomBarHeightConstraint SbKZyzHjiALdtzLd
#define openSomeTheAppWithWKWebView MtVcEQWVzIpTCDNy
#define openOtherAppWithWKWebView YyFyMfJjHpSPKGRK
#define whitelist udYRkIBCCRjgNUrZ
#define rulesString yUiyllOaYZPxsmgT
#define alertController PiQIcUNjrjxUOHzz
#define ADReachability bIJNxYQyMBuGAMcq
#define xReachabilityChangedNotification IbibszYsICTMfRyh
#define reachabilityWithHostName BldMQYmQiljseTpz
#define reachabilityWithAddress ZspLQwkBtPlxzPFW
#define reachabilityForInternetConnection mrVVrCIkxnjakdaa
#define startNotifier nMUBpksedglaVDHA
#define stopNotifier thJMmiWfiBtpwLaX
#define currentReachabilityStatus ZlWrPaLbQZcuvNdJ
#define connectionRequired MgOaksHCgrgAAufN
#define PrintReachabilityFlags eMvvXUgFsbjCXnfD
#define ReachabilityCallback spzafyNvZrzPQvIL
#define noteObject YhNEQCwYgqRlfPAQ
#define _reachabilityRef fFYnbinfbhjmhiYb
#define returnValue yzPKqaEtrcLhbbYm
#define reachability UYhIjznzsZeTznwH
#define zeroAddress gbpPeHeUYeFAeWQe
#define networkStatusForFlags cuSBfUhpqxaAZTTv
#define BaseViewController LJjaWHwEAlITawuW
#define BaseTableViewController lEDTzkTLUEzYdpzm
#define SideMenuViewController eEdWSzxQxITZerhx
#define HomeViewController blsVGCMQxwZeuLhN
#define HomeTableViewCell VyNjVvDDtEFWkiKw
#define DataListViewController JUHnSIVJKCTWNkSy
#define BookmarkViewController RERCoovkKoJdVKTx
#define MoreViewController GKBcvXAtrCAMgjjZ
#define MoreAppCell KhpnTPOatWPYBRjz
#define DetailViewController UjDGpdnDeocGoLbo
#define TOActivityChrome wjnaprwWPERppXRO
#define TOActivitySafari QsesdAFQRpSYTVWJ
#define TOWebViewController jFBJzZoBEpftFNdg
#define TermsPrivacyViewController lvorWqtxemMTluSf
#define wkView UqZaxIYXYxqaiAjK
#define YesBtn njYhbtktPLTFPHMF
#define NoBtn FuRQIHsaAnHIGEjq
#define wkTrailing CKVHjTSzYYrQHLPO
#define wkTop lQzaNymwjNaHeZiU
#define wkBottom CECWvenfArEgAlmR
#define btnWidth xEnIYbCHZxfPnjpI
#define naviPages hVCciBoGeEnhPGzu
#define OverWebViewController qjNEBTipbQhGcUqu
#define titleView KQwFnBAkSGJgLTHu
#define titleLabel UDNWNRoSiWwxpwZS
#define toolsView HiDFPmPLHHpnzyAc
#define backBtn QtpYhnGMeHadUUEg
#define forwardBtn bnzNxprZqGAlggPl
#define refreshBtn sINcjFmZqiaLenKV
#define shareBtn LvEtpVUFZwwEUlOK
#endif
